"""empty message

Revision ID: 5bcc8eccf5e2
Revises: c769927efb38
Create Date: 2026-02-25 12:31:21.593831

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '5bcc8eccf5e2'
down_revision: Union[str, Sequence[str], None] = 'c769927efb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
