version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    ports:
      - '8000:8000'
    volumes:
      - ..:/app
    command: /bin/bash -c "sleep 10 && ALEMBIC_CONFIG=src/alembic.ini alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - app-network

  db:
    restart: always
    image: postgres:14-alpine
    user: ${POSTGRES_USER}
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: worker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ..:/app
    command: arq src.infrastructure.worker.config.WorkerSettings
    networks:
      - app-network

  redis:
    image: redis:7.0.2-alpine
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
